language: ruby
cache: bundler
dist: xenial

bundler_args: --jobs 7 --without docs debug

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

rvm:
  - 2.5.3
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
script: bundle exec rake
